disabled_rules: 
- anyobject_protocol # https://stackoverflow.com/questions/30176814/whats-the-difference-between-a-protocol-extended-from-anyobject-and-a-class-onl/32895975#32895975 
- missing_docs 
- no_extension_access_modifier 
- no_grouping_extension 
- object_literal 
- vertical_whitespace_closing_braces 
- vertical_whitespace_opening_braces 
- unowned_variable_capture 
- multiline_arguments_brackets 
- multiline_parameters_brackets 
- multiline_literal_brackets 
- attributes # @available на отдельной строке 
- file_types_order 
- discouraged_optional_collection 
- identifier_name
- lower_acl_than_parent 
- trailing_closure 
- force_unwrapping 
- todo
- nimble_operator
- type_name
- closure_parameter_position
- generic_type_name

opt_in_rules: 
- array_init 
- closure_body_length 
- closure_end_indentation 
- closure_spacing 
- collection_alignment 
- contains_over_first_not_nil 
- convenience_type 
- discouraged_object_literal 
- discouraged_optional_boolean 
- empty_count 
- empty_string 
- empty_xctest_method 
- explicit_init 
- fatal_error_message 
- first_where 
- function_default_parameter_at_end 
- identical_operands 
- implicit_return 
- joined_default_parameter 
- last_where 
- legacy_multiple 
- legacy_random 
- let_var_whitespace 
- literal_expression_end_indentation 
- modifier_order 
- multiline_arguments 
- multiline_function_chains 
- multiline_parameters 
- nimble_operator 
- nslocalizedstring_key 
- nslocalizedstring_require_bundle 
- operator_usage_whitespace 
- overridden_super_call 
- prohibited_super_call 
- pattern_matching_keywords 
- private_action 
- private_outlet 
- reduce_into 
- redundant_nil_coalescing 
- redundant_type_annotation 
- required_enum_case 
- sorted_first_last 
- static_operator 
# - switch_case_on_newline # ⚠️ Требует обсуждения 
- toggle_bool 
- unneeded_parentheses_in_closure_argument 
- untyped_error_in_catch 
- vertical_parameter_alignment_on_call 
- vertical_whitespace_between_cases 
- xct_specific_matcher
- sorted_imports

analyzer_rules:
  - unused_import 
 
excluded: # paths to ignore during linting. Takes precedence over included. 
- Carthage 
- Pods 
- "Packages/**/Generated/*.swift"
- swift-templates
- "**/*.generated.swift"

# # configurable rules can be customized from this configuration file 
# # binary rules can set their severity level 
trailing_semicolon: error 
return_arrow_whitespace: error 
 
# line_length: 140 
 
closure_body_length: 
- 20 # warning 
- 100 # error
