name: "Wake on LAN"

settings:
  base:
    SWIFT_VERSION: 5.2
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    ENABLE_BITCODE: NO

options:
  deploymentTarget:
    iOS: 11.0

attributes:
  CLASSPREFIX: WO
  ORGANIZATIONNAME: "Владислав Лисянский"

targets:
  Wake on LAN:
    platform: iOS
    type: application
    sources:
      - path: "Wake on LAN"
    dependencies:
      - carthage: SnapKit
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        DISPLAY_NAME: "Wake on LAN"

        DEVELOPMENT_TEAM: 3HSG7M3SCR
        PRODUCT_BUNDLE_IDENTIFIER: com.tr1ckyf0x.wakeonlan
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        PROVISIONING_PROFILE_SPECIFIER: ""
    # postBuildScripts:
    #   - name: "Crashlytics"
    #     script: |
    #             ${PODS_ROOT}/FirebaseCrashlytics/run
    #     inputFiles:
    #       - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
    #       - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)