name: "Wake on LAN"

settings:
  base:
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    ENABLE_BITCODE: NO
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    CLANG_ANALYZER_LOCALIZABILITY_EMPTY_CONTEXT: YES
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES

options:
  deploymentTarget:
    iOS: 12.0

attributes:
  CLASSPREFIX: WO
  ORGANIZATIONNAME: "Владислав Лисянский"

packages:
  FirebaseAnalytics:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 8.0.0
  FirebaseCrashlytics:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 8.0.0
  Reachability:
    url: https://github.com/ashleymills/Reachability.swift
    from: 5.0.0
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.0.0
  CocoaLumberjackSwift:
    url: https://github.com/CocoaLumberjack/CocoaLumberjack
    from: 3.7.0

targets:
  Wake on LAN:
    platform: iOS
    type: application
    sources:
      - path: "Wake on LAN"
        excludes:
          - "**/*.secret"
          - "Modules/**/"
        optional: true
    dependencies:
      - package: FirebaseAnalytics
      - package: FirebaseCrashlytics
      - package: Reachability
      - package: SnapKit
      - package: CocoaLumberjackSwift
      - target: AddHost
      - target: CoreDataService
      - target: HostList
      - target: SharedExtensions
      - target: SharedProtocols
      - target: SharedModels
      - target: WakeOnLanService
      - target: WOLResources
      - target: WOLUIComponents

    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        DISPLAY_NAME: "Wake on LAN"
        DEVELOPMENT_TEAM: SGM5527A99
        PRODUCT_BUNDLE_IDENTIFIER: com.tr1ckyf0x.wake-on-lan
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Manual
        PROVISIONING_PROFILE_SPECIFIER: "Wake On Lan Development"
        INFOPLIST_FILE: "Wake on LAN/Info.plist"
        OTHER_LDFLAGS: $(inherited) -ObjC
    preBuildScripts:
    - name: "Swiftlint"
      script: |
              if which swiftlint >/dev/null; then
                swiftlint
              else
                echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
              fi
    postBuildScripts:
      - name: "Crashlytics"
        script: |
                ${BUILD_DIR%Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run
        inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
          - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
  WakeOnLanTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: "Wake On LAN Tests"
    dependencies:
      - target: "Wake on LAN"
      - framework: "Carthage/Build/Nimble.xcframework"
      - framework: "Carthage/Build/Quick.xcframework"

  AddHost:
    templates:
      - Framework
    templateAttributes:
      frameworkName: AddHost
    dependencies:
      - package: CocoaLumberjackSwift
      - package: SnapKit
      - target: CoreDataService
      - target: SharedExtensions
      - target: SharedModels
      - target: SharedProtocols
      - target: WOLResources
      - target: WOLUIComponents
    sources:
      - path: "Wake on LAN/Modules/${frameworkName}"

  CoreDataService:
    templates:
      - Framework
    templateAttributes:
      frameworkName: CoreDataService
    dependencies:
      - package: CocoaLumberjackSwift
      - target: SharedModels
      - target: SharedProtocols
    sources:
      - path: "Wake on LAN/Modules/${frameworkName}"

  HostList:
    templates:
      - Framework
    templateAttributes:
      frameworkName: HostList
    dependencies:
      - package: CocoaLumberjackSwift
      - package: Reachability
      - package: SnapKit
      - target: AddHost # TODO: Remove dependency, use protocol
      - target: CoreDataService
      - target: SharedExtensions
      - target: SharedModels
      - target: SharedProtocols
      - target: WOLResources
      - target: WOLUIComponents
      - target: WakeOnLanService
    sources:
      - path: "Wake on LAN/Modules/${frameworkName}"
    
  SharedExtensions:
    templates:
      - Framework
    templateAttributes:
      frameworkName: SharedExtensions
    dependencies:
      - package: SnapKit
      - target: WOLResources
    sources:
      - path: "Wake on LAN/Modules/${frameworkName}"

  SharedProtocols:
    templates:
      - Framework
    templateAttributes:
      frameworkName: SharedProtocols
    dependencies:
      - target: SharedModels
    sources:
      - path: "Wake on LAN/Modules/${frameworkName}"
  
  SharedModels:
    templates:
      - Framework
    templateAttributes:
      frameworkName: SharedModels
    dependencies:
      - target: WOLResources
    sources:
      - path: "Wake on LAN/Modules/${frameworkName}"
      
  WOLResources:
    templates:
      - Framework
    templateAttributes:
      frameworkName: WOLResources
    sources:
      - path: "Wake on LAN/Modules/${frameworkName}"
      - path: "Wake on LAN/Modules/${frameworkName}/Generated/R.generated.swift"
        optional: true
        createIntermediateGroups: true
    preBuildScripts:
    - name: "R.Swift"
      script: |
              "$PODS_ROOT/R.swift/rswift" generate --accessLevel public "$SRCROOT/Wake on LAN/Modules/${frameworkName}/Generated/R.generated.swift"
      inputFiles:
        - $TEMP_DIR/rswift-lastrun
      outputFiles:
        - $SRCROOT/Wake on LAN/Modules/${frameworkName}/Generated/R.generated.swift
  
  WOLUIComponents:
    templates:
      - Framework
    templateAttributes:
      frameworkName: WOLUIComponents
    dependencies:
      - package: SnapKit
      - target: SharedModels
      - target: WOLResources
      - target: SharedExtensions
    sources:
      - path: "Wake on LAN/Modules/${frameworkName}"
  
  WakeOnLanService:
    templates:
      - Framework
    templateAttributes:
      frameworkName: WakeOnLanService
    dependencies:
      - target: CoreDataService
      - target: WOLResources
    sources:
      - path: "Wake on LAN/Modules/${frameworkName}"

targetTemplates:
  Framework:
    settings:
      base:
        INFOPLIST_FILE: "Wake on LAN/Modules/${frameworkName}/Info.plist"
        PRODUCT_BUNDLE_IDENTIFIER: com.tr1ckyf0x.wakeonlan.${frameworkName}
        CODE_SIGN_IDENTITY: ""
        CODE_SIGN_STYLE: Automatic
        PROVISIONING_PROFILE_SPECIFIER: "Automatic"
    platform: iOS
    type: framework
