name: "Wake on LAN"

configs:
  AppStore Debug: debug
  AppStore Release: release
  AdHoc Debug: debug
  AdHoc Release: release

settings:
  base:
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    ENABLE_BITCODE: NO
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    CLANG_ANALYZER_LOCALIZABILITY_EMPTY_CONTEXT: YES
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
    DEVELOPMENT_TEAM: SGM5527A99
    CODE_SIGN_STYLE: Manual
    MARKETING_VERSION: 1.4.0
    CURRENT_PROJECT_VERSION: 1

options:
  deploymentTarget:
    iOS: 13.0

attributes:
  ORGANIZATIONNAME: "Владислав Лисянский"

targets:
  Wake on LAN:
    platform: iOS
    type: application
    sources:
      - path: "Wake on LAN"
        excludes:
          - "**/*.secret"
          - "Modules/**/"
        optional: true
      - IntentSharedSources
    dependencies:
      - target: Intent
    scheme:
      configVariants:
        - AppStore
        - AdHoc

    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        DISPLAY_NAME: "Awake"
        INFOPLIST_FILE: "Wake on LAN/Info.plist"
        OTHER_LDFLAGS: $(inherited) -ObjC
        PRODUCT_BUNDLE_IDENTIFIER: com.tr1ckyf0x.wake-on-lan
        CODE_SIGN_ENTITLEMENTS: "Wake on LAN/Wake on LAN.entitlements"
      configs:
        AppStore Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
          PROVISIONING_PROFILE_SPECIFIER: "Wake On Lan Development"
        AppStore Release:
          CODE_SIGN_IDENTITY: "Apple Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "Wake On Lan AppStore"
        AdHoc Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
          PROVISIONING_PROFILE_SPECIFIER: "Wake On Lan Development"
        AdHoc Release:
          CODE_SIGN_IDENTITY: "Apple Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "Wake On Lan AdHoc"
    preBuildScripts:
    - name: "Swiftlint"
      basedOnDependencyAnalysis: false
      script: |
              .bin/swiftlint
    postBuildScripts:
      - name: "Crashlytics"
        basedOnDependencyAnalysis: false
        script: |
                ${PODS_ROOT}/FirebaseCrashlytics/run
        inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
          - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
  Intent:
    platform: iOS
    type: app-extension
    sources:
      - Intent
      - IntentSharedSources
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        DISPLAY_NAME: "Awake Intent"
        INFOPLIST_FILE: "Intent/Info.plist"
        PRODUCT_BUNDLE_IDENTIFIER: com.tr1ckyf0x.wake-on-lan.intent
        CODE_SIGN_ENTITLEMENTS: "Intent/Intent.entitlements"
      configs:
        AppStore Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
          PROVISIONING_PROFILE_SPECIFIER: "Wake On Lan Siri Intent Development"
        AppStore Release:
          CODE_SIGN_IDENTITY: "Apple Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "Wake On Lan Siri Intent AppStore"
        AdHoc Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
          PROVISIONING_PROFILE_SPECIFIER: "Wake On Lan Siri Intent Development"
        AdHoc Release:
          CODE_SIGN_IDENTITY: "Apple Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "Wake On Lan Siri Intent AdHoc"
    dependencies:
      - sdk: Intents.framework
    scheme:
      configVariants:
        - AppStore
        - AdHoc
