# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(
      scheme: "Wake on LAN AppStore",
      include_bitcode: false,
      export_options: {
        provisioningProfiles: { 
          "com.tr1ckyf0x.wake-on-lan" => "Wake On Lan AppStore"
        }
      }
    )

    app_store_connect_api_key(
      key_id: "65K8M54759",
      issuer_id: "39222a33-4915-477e-a282-57c970346695",
      key_filepath: "fastlane/AuthKey_65K8M54759.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
